#!/usr/bin/env bash

set -e

source $SNAP/actions/common/utils.sh

KUBECTL="$SNAP/microk8s-kubectl.wrapper"

KUBECTL_DELETE_ARGS="--wait=true --timeout=180s --ignore-not-found=true"

echo "Disabling Keystone Auth..."

$KUBECTL delete $KUBECTL_DELETE_ARGS -n kube-system deployment.apps/k8s-keystone-auth
$KUBECTL delete $KUBECTL_DELETE_ARGS -n kube-system service/k8s-keystone-auth-service 


echo "Keystone Auth deployment is disabled"