#!/usr/bin/env python3

import subprocess
import click
import os
import sys

sys.path.append('../common')

from addons.common.utils import ensure_addon

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
HELM = os.path.expandvars("$SNAP/microk8s-helm3.wrapper")
NAMESPACE = "ccsi"

@click.command()
@click.option("--values", required=True)
def main(
    values: str,
):
    """
    Enable the openstack-cloud-controller-manager addon.
    """

    ensure_addon("rbac")

    subprocess.run(
        [
            HELM,
            "repo",
            "add",
            "cpo",
            "https://kubernetes.github.io/cloud-provider-openstack",
        ]
    )
    subprocess.run([HELM, "repo", "update"])

    click.echo(f"Creating {NAMESPACE} namespace...")
    subprocess.run(f"{KUBECTL} create namespace {NAMESPACE}".split())

    subprocess.run(
        [
            HELM,
            "install",
            "-n",
            NAMESPACE,
            "cinder-csi",
            "cpo/openstack-cinder-csi",
            "--values",
            values,
        ]
    )

    click.echo(
        f"""
=============================================================
Cinder CSI has been installed and will be available shortly.
"""
    )


if __name__ == "__main__":
    main()
